import './sail/core/sail.core.js';
import './sail/core/sail.viewer.js';
import './sail/core/sail.utils.js';
import './sail/core/sail.io.js';
import './sail/core/sail.dialog.js';
import './sail/core/sail.director.js';
import './sail/core/sail.entrace.js';
import './sail/core/sail.scene.js';
import '../laya/src/ui/layaUI.max.all.js';
